import '@vue-design/theme-2n/dist/base.css'
import '@vue-design/theme-2n/dist/slider.css'
import '@vue-design/theme-2n/dist/input-number.css'
import '@vue-design/theme-2n/dist/input.css'
import '@vue-design/theme-2n/dist/tooltip.css'
import '@vue-design/theme-2n/dist/popper.css'
