import '@vue-design/theme-2n/dist/base.css'
import '@vue-design/theme-2n/dist/date-picker.css'
import '@vue-design/theme-2n/dist/input.css'
import '@vue-design/theme-2n/dist/scrollbar.css'
import '@vue-design/theme-2n/dist/popper.css'
import '@vue-design/theme-2n/dist/button.css'
