import '@vue-design/theme-2n/dist/base.css'
import '@vue-design/theme-2n/dist/table.css'
import '@vue-design/theme-2n/dist/checkbox.css'
import '@vue-design/theme-2n/dist/tag.css'
import '@vue-design/theme-2n/dist/tooltip.css'
import '@vue-design/theme-2n/dist/scrollbar.css'
