import '@vue-design/theme-2n/src/base.scss'
import '@vue-design/theme-2n/src/table.scss'
import '@vue-design/theme-2n/src/checkbox.scss'
import '@vue-design/theme-2n/src/tag.scss'
import '@vue-design/theme-2n/src/tooltip.scss'
import '@vue-design/theme-2n/src/scrollbar.scss'
