import '@vue-design/theme-2n/dist/base.css'
import '@vue-design/theme-2n/dist/transfer.css'
import '@vue-design/theme-2n/dist/input.css'
import '@vue-design/theme-2n/dist/button.css'
import '@vue-design/theme-2n/dist/checkbox.css'
import '@vue-design/theme-2n/dist/checkbox-group.css'
